experiment_name: awr_beta1

train_npz: ../data/processed/electronics_seq50_xxxxx/rl_train.npz
iql_ckpt: ../models/iql_discrete_gamma0.95_tau0.7.pt
output_root: ../runs

beta: 1.0
max_weight: 20.0

epochs: 5
batch_size: 4096
lr: 0.0003
grad_clip: 10.0

emb_dim: 64